### ISSUE TITLE
Can't install CONCOCT on macos via Docker

### ISSUE THREAD

**Issue by yoyohashao** [BinPro/CONCOCT#138]
Dear all, as in my previous post, I couldn't get CONCOCT start in anaconda so I tried Docker. But when I trying to download the image, an error came up:
bash-3.2$ sudo docker run -v /home/USER/Data:/opt/Data -i -t binpro/concoct_latest bash
FATA[0000] Post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

Also, when i try to look up the complete workflow(https://concoct.readthedocs.org/en/latest/doc/complete_example.rst), it shows the content I am looking for doesn't exist...

Any suggestion is welcome.

Cheers,
Fang

**Comment by alneberg** [comment]
Hello @yoyohashao, 

I will investigate the docker error further and try to get back to you. The error with the docs seems to be a wrong link, it should be ".html" instead of ".rst". Can you please tell me where you found this link so that I can correct it.

Thanks,
Johannes

**Comment by yoyohashao** [comment]
Dear Johannes,
The link was found on a software installation page (https://concoct.readthedocs.org/en/latest/installation.html#id1 <https://concoct.readthedocs.org/en/latest/installation.html#id1>) ,the command line is :sudo docker run -v /home/USER/Data:/opt/Data -i -t binpro/concoct_latest bash
Thanks.


Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37

**Comment by alneberg** [comment]
@yoyohashao, Are you still interested in solving this issue? It looks like in the command you were using to start docker you should switch USER with your user name. It tries to give docker access to the directory Data in your home directory so that directory needs to be created.

Cheers,
Johannes

**Comment by yoyohashao** [comment]
Hello Johannes,
 I am running CONCOCT with ANACONDA. The user name issue you mentioned makes sense but I am not sure if i actually typed USER as username. I probably just copied the commander line on the web page to show you which command I use (well , obviously I should have given the command line in my Terminal, #misunderstanding ;( )

But thanks for emailing me anyway. Now I can run CONCOCT on my Mac.

Best,

Fang



Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37 <https://www.researchgate.net/profile/Fang_Liu37>

**Comment by alneberg** [comment]
Ok great that you're able to use CONCOCT! I would say anaconda is the preferred way to get it running so its good you gave that another try.
