### ISSUE TITLE
MAX_LINE_LENGTH in vbgmmodule.h

### ISSUE THREAD

**Issue by lch14forever** [BinPro/CONCOCT#139]
In vbgmmodule.h, the maximal line length is defined as 10000
#define MAX_LINE_LENGTH   10000
This may cause an issue with large input files.

**Comment by alneberg** [comment]
Hi @lch14forever!

Thanks for reporting! I see that this can be a problem, just out of curiosity, have this caused a problem for you yet and in that case, how many samples (and which kmer length) were you using? 

Cheers,
Johannes

**Comment by lch14forever** [comment]
Hi Johannes,

We did encounter problems and found that could be the potential cause. We were trying to analyse hundreds of samples from multiple studies. Would you recommend to analyse them separately?


Thanks,
Chenhao.

**Comment by chrisquince** [comment]
Hi,

I have changed the C code so that the default max line length is 1048576 bytes or 1 MiB. I have also made the memory allocation of the lines dynamic so that this can simply be increased further if need be.

Thanks,
Chris

**Comment by alneberg** [comment]
@lch14forever Can you please confirm that the current master solves the issue?

Cheers,
Johannes

**Comment by lch14forever** [comment]
Yes. This solves the problem. 
It seems that the vbgmm stage takes extremely long to run. Do you have any idea how scalable the method is?

Thanks,
Chenhao.

**Comment by alneberg** [comment]
Great @lch14forever!

I am afraid we've seen poor time performance on large datasets as well. There are some tricks you can do to speed it up, but you will risk lowering the clustering performance. Otherwise you just need some patience.
