### ISSUE TITLE
Trying to evaluate concoct output. Error in read file

### ISSUE THREAD

**Issue by yoyohashao** [BinPro/CONCOCT#141]
SEBASTIANs-MacBook-Pro:evaluation-concoct FLFLFLLF$ Rscript /Users/FLFLFLLF/Documents/CONCOCT-0.4.0/scripts/ClusterPlot.R -c /Users/FLFLFLLF/tsmg/concoctOUT/clustering_gt1000.csv -p /Users/FLFLFLLF/tsmg/concoctOUT/pca_means_gt1000.csv -r /Users/FLFLFLLF/tsmg/concoctOUT/pca_variances_gt1000_dim -l -o tsmgconcoctClusterPlot.pdf
Loading required package: methods
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  'file' must be a character string or connection
Calls: read.csv -> read.table
Execution halted

Dear admin,
So this is my first time to try CONCOCT on my own data. Seems like there's something wrong with file format? But I didn't change anything of concoct output. Can you tell me why? Thanks!

**Comment by alneberg** [comment]
Hi @yoyohashao,

I will look into this issue further, but I can say that we don't use ClusterPlot.R at the moment, it will show you the clusters in the first two pca dimensions and while that might be interesting, we've not had any particular use for it so far and this script might be removed in a future version. I would recommend you to continue to generate the COG Plot following the instructions here: https://concoct.readthedocs.org/en/latest/complete_example.html#validation-using-single-copy-core-genes

Cheers,
Johannes
