### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by yoyohashao** [BinPro/CONCOCT#146]
Dear Johannes,

After successfully running CONCOCT on my several datasets, today I hit a rock. It says:

![image](https://cloud.githubusercontent.com/assets/7657231/7744285/a6b28156-ffd4-11e4-9b34-56e2342e87ae.png)

My fasta file and coverage file are all in UTF-8 format. The only thing different than usual is I removed contigs shorter than 300bp in my fasta file using mothur. 

The files I used can be downloaded via 
https://drive.google.com/file/d/0B_JVazsg7l0yR085WnRlWG1lcDg/view?usp=sharing
https://drive.google.com/file/d/0B_JVazsg7l0yTDYzVjUzLXQ2X00/view?usp=sharing

Many thanks!

**Comment by alneberg** [comment]
Hi @yoyohashao,

I can confirm that I can reproduce your error. I will investigate further what could be the issue. I see that you only use coverage from one sample. While this is possible, I wouldn't recommend it since it will probably not perform particularly good.

**Comment by yoyohashao** [comment]
Thanks for the replay Johannes. 
I am using CONCOCT as a way of removing contamination of my single-cell genomes.That’s why there’s only one sample. One of my friends said she used this to bin the target genomes from single-cell datasets so I just followed her suggestion as I am not a skilled bioinformatician.
   I also test CONCOCT on one metagenome and it generates a few meaningful bins. Due to some uncontrollable reasons, all metagenome datasets in our lab have no biological replicates. I couldn’t imagine how the command would look like if there are multiple samples, do I need to type multiple coverage file names and composition file names in one command or I have to combine the files into one coverage file and one composition file? 
 
Cheers,

Fang

Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37

**Comment by alneberg** [comment]
That's interesting! I've no experience of single cell sequencing but I think I've found your issue. It seems like the coverage file is malformed, it should contain one header line and only one tab between columns. To include multiple samples you would only add more columns in the coverage file. Its actually more valuable to include samples that are not true replicates but samples from a similar environment.

Cheers,
Johannes

**Comment by yoyohashao** [comment]
Hi Johannes,
Things just got really odd here. 
The command I used to generate coverage file is 

cat FASTAFILE | grep "^>" | awk -F "\_" '{print $0"\t"$6}' > coverage.cov  

then I used find&replace to remove the ‘>’ of each name line.
 I don’t really know why this command never works. 
I upload my previous fasta and workable coverage file (https://drive.google.com/file/d/0B_JVazsg7l0yN0ZzS0tHMzg0QkU/view?usp=sharing , https://drive.google.com/file/d/0B_JVazsg7l0ySWtHaTg1aUEwVVE/view?usp=sharing).

 I didn’t know there should be a header line of coverage file but the old coverage file worked. From what I can see, there’s no difference between my new fasta file and old fast file, format wise. But maybe you can find something different. Thanks! 

As for multi samples, all my 6 single-cell datasets are from the same tissue (similar environment ) , if I combine them then run CONCOCT, could I know which bin comes from which dataset? Now I feel generating coverage files can be a tricky step. I am looking forward to hearing more from you.

Cheers
Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37

**Comment by yoyohashao** [comment]
Hi, I noticed in my last email I forgot to mention even I deleted that
extra empty column, the file didn't work. So I wonder what's your method to
generate coverage files. Hope my problem doesn't bother you much. Thanks

Best,
Fang

**Comment by alneberg** [comment]
Issue likely not valid anymore since version of concoct has changed a lot.
