### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by Stephaniedv** [BinPro/CONCOCT#160]
Hi,

I submit this
module load python/x86_64/2.7.2
	concoct -c 40 --coverage_file final_contigs_cuttofragments_PE_and_SE_sorted_duplicatesremoved.coverage.percontig.tsv --composition_file final_contigs_contigs_cuttofragments.fasta -b concoct-output/

and get this error:
/software/shared/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/biopython-1.65-py2.7-linux-x86_64.egg/Bio/Seq.py:342: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)
Traceback (most recent call last):
  File "/software/shared/apps/x86_64/python/2.7.2/bin//concoct", line 5, in <module>
    pkg_resources.run_script('concoct==0.4.0', 'concoct')
  File "/software/shared/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 698, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/software/shared/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py", line 1616, in run_script
    exec(code, namespace, namespace)
  File "/shared/clssoft/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 76, in <module>
    results = main(args)
  File "/shared/clssoft/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 20, in main
    composition, cov, cov_range = load_data(args)
  File "/software/shared/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 25, in load_data
    read_length = args.read_length
  File "/software/shared/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 87, in load_coverage
    cov_range = (cov.columns[0],cov.columns[-1])
  File "/software/shared/apps/x86_64/python/2.7.2/lib/python2.7/site-packages/pandas/core/index.py", line 1149, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0

Does anyone know what could be causing this?
I have a fasta file and a 2-column file with contig names and coverages as input. Should the coverages be integers? Should I build an index? Thank you for any ideas

**Comment by alneberg** [comment]
Hi @Stephaniedv,

I can't figure out completely what's going on based on the information you gave me but there seems to be some problem reading your coverage file. More specifically concoct has troubles identifying any columns in the coverage file. Is it tab separated?

I can make a more thorough debug effort if you send me some test data that can replicate the error.

Cheers,
Johannes Alneberg

**Comment by Stephaniedv** [comment]
thank you, that was exactly it! I changed it and it worked :)

**Comment by alneberg** [comment]
Glad I could help!

**Comment by Stephaniedv** [comment]
Dear Johannes, 

One more question, I hope you don't mind. 
Concoct is running, but has been running for over 4 days now. 
In the output folder, there are these files: 
-rw-r--r--+ 1 stvos aflp 500 Jun 3 13:51 args.txt 
-rw-r--r--+ 1 stvos aflp 693 Jun 3 14:03 log.txt 
-rw-r--r--+ 1 stvos aflp 276M Jun 3 14:02 original_data_gt1000.csv 
-rw-r--r--+ 1 stvos aflp 140K Jun 3 14:03 PCA_components_data_gt1000.csv 
-rw-r--r--+ 1 stvos aflp 133M Jun 3 14:03 PCA_transformed_data_gt1000.csv 

No sign of a clustering file yet. 
Concoct stays within memory settings (8Gb) and uses quite a lot of CPU, but this cluster can handle that. 
I must say our input files are quite big: 
-rw-r--r--+ 1 stvos aflp 742M Jun 1 11:28 final_contigs_rm_mt_extractedscaffolds_contigs_cuttofragments.fasta 
-rwxr-xr-x+ 1 stvos aflp 6.7M Jun 3 13:48 final_contigs_rm_mt_extractedscaffolds_cuttofragments.fasta_PE_and_SE_sorted_duplicatesremoved.coverage.percontig.tsv 

Does this long run seem normal to you, regarding the size of the input files? 
I submitted the concoct command with default parameters, without setting the amount of cluster or iterations. 
We are expecting one large cluster (main arthropod genome) and one cluster containing bacteria, algae, etc. 

With kind regards and thank you in advance for your opinion, 

Stephanie

**Comment by alneberg** [comment]
Sure!

Yes its not a completely strange amount of time used, although I cannot really tell from the file sizes only how long time I would expect. I don't spot anything abnormal in your output files so I would just recommend you to wait for concoct to finish.

Cheers,
johannes

**Comment by Stephaniedv** [comment]
ok! 

Thanks loads, also for such a quick response. 

Stéphanie
