### ISSUE TITLE
Best way to set MRKDUP?

### ISSUE THREAD

**Issue by bstamps** [BinPro/CONCOCT#161]
Hello, currently getting the below error when trying to run map-bowtie2-markduplicates.sh: 

/home/ubuntu/bin/CONCOCT/scripts/map-bowtie2-markduplicates.sh: line 97: MRKDUP: unbound variable

The most recent version of picard tools does not supply a MarkDuplicates.jar, and instead invokes the command through picard.jar. What's the best way to get this working?

**Comment by alneberg** [comment]
Hi @bstamps,

thanks for giving us a heads up on this. I guess we need to rewrite the lines where picard is called in that script. I will have a look at it but as a quick fix for you I don't think its too difficult for you to manually change the command if you already know the correct command syntax.

Let me know if you need any assistance.

**Comment by shannonmargaret** [comment]
I ran into the same issue I'm guessing to resolve this you set $MRKDUP= java -jar MarkDuplicates
however in the map-bowtie2-markduplicates.sh $MRKDUP is being called as

 java -Xms1g -Xmx24g -XX:ParallelGCThreads=$THREADS -XX:MaxPermSize=1g -XX:+CMSClassUnloadingEnabled \
    -jar $MRKDUP \


so then it seems as though one should set $MRKDUP as Markduplicates??? Is this correct?  Some guidance on what exactly to change is much appreciated.

**Comment by alneberg** [comment]
Hello @shannonmargaret,

the MRKDUP variable used to contain the path for the markduplicates .jar file, however with the new picard syntax, I'm guessing you could set it to:

    export MRKDUP="<full path to picard.jar> MarkDuplicates"

I haven't tested this though. Another option, If you wish, is to run bowtie2 and markduplicates without using the convenience script map-bowtie2-markduplicates.sh.

Best regards,
Johannes

**Comment by seasyhuang** [comment]
Exporting the MRKDUP variable like @alneberg suggested didn't work for me.

**Comment by seasyhuang** [comment]
In my ~/.bashrc, I set:
`export MRKDUP="/home/seasy/picard-2.18.6/picard.jar MarkDuplicates"`

But when I run the script, I get this at every iteration:
`/home/seasy/scratch/CONCOCT-0.4.0/scripts/map-bowtie2-markduplicates.sh: line 97: [: /home/seasy/picard-2.18.6/picard.jar: binary operator expected`
