### ISSUE TITLE
different output plot generated by ClusterPlot.R in version 0.4.0

### ISSUE THREAD

**Issue by AlisonF** [BinPro/CONCOCT#162]
Hi, 

I was using CONCOCT version 0.4.0 to run the test data set https://github.com/BinPro/CONCOCT-test-data/releases. I was getting a completely different plot from the example after running ClusterPlot.R, where there were 16 clusters in the plot that I generated 
[ClusterPlot_data0.3.2.pdf](https://github.com/BinPro/CONCOCT/files/440186/ClusterPlot_data0.3.2.pdf)
and only 4 in the example 
[ClusterPlot_0.3.2.pdf](https://github.com/BinPro/CONCOCT/files/440187/ClusterPlot_0.3.2.pdf)
I know that using newer versions may generate different results, but feel a little suspicious on how different versions would make such huge difference. I didn't encounter any error during the process. Could you please let me know if it looked right to you and what might be the problem if there is any? Thank you very much!

Best,

Alison

**Comment by alneberg** [comment]
Hi Alison,

I will look into this but I need you to clarify a bit what you have done. Did you use different versions of the CONCOCT program or different versions of the data? Which versions in that case? 

The plots you sent me does indeed look very different, but I can't really guess from the file names, what differs in how you generated them.

Cheers,
Johannes

**Comment by AlisonF** [comment]
Hi Johannes, 

Thanks for the reply. I used **CONCOCT version 0.4.0** to run **test data set 0.3.2**. Therefore I named the plot "ClusterPlot_data0.3.2.pdf". Sorry about the confusion. In fact, I ran **test data set 0.2.0** with **CONCOCT version 0.4.0** again and got the exact same plot with 16 clusters [ClusterPlot_data0.2.0.pdf](https://github.com/BinPro/CONCOCT/files/442604/ClusterPlot_data0.2.0.pdf) So I went back to check these two data sets and found that files of $CONCOCT_TEST/reads/Sample*.fa in these two data set versions were the same. That might explain why the plots generated by CONCOCT version 0.4.0 looked same. But they are both different from the example plots (4 clusters only) downloaded from this link: https://github.com/BinPro/CONCOCT-test-data/releases. Could you please let me know what the issue might be? I hope it's more clear this time. Thanks a lot!

Best,

Alison

**Comment by alneberg** [comment]
Hi, it's getting clearer. 

Did you follow the [tutorial](https://concoct.readthedocs.io/en/latest/complete_example.html)? 

I tried running both CONCOCT and ClusterPlot.R version 0.4.0 on test data 0.3.2, but without being able to reproduce your results. It alls seems to work for me. 

Can you post the output from `ls` in your concoct output directory? That will tell how many clusters you got from running concoct. 

Maybe you can try and rerunning concoct and making sure you use the command listed in the tutorial. If you still get 16 clusters we have to look at the input data you've generated.

That would help me nail down what is happening. 

Thanks,
Johannes

**Comment by AlisonF** [comment]
Yes I followed the tutorial and made sure that all commands I used was the same as tutorial except two things:
**1.** I used full paths rather than setting variables as suggested in the tutorial. For example, when the tutorial says: 
cat $CONCOCT_TEST/reads/Sample*_R1.fa > All_R1.fa
I would do:
cat my/full/path/to/CONCOCT_test_data_0.3.2/reads/Sample*_R1.fa > All_R1.fa

**2.** When I ran ClusterPlot.R, it gave me an error of: **Error: could not find function "opts"**
Therefore, I modified the code:
**opts(legend.text=theme_text(size=4))**
to
**labs(plot.title = element_text(size=4))**
But I don't think the are the reasons that it's giving me 16 clusters.

Here are the files in my concoct output directory:
![concoct-output_mine](https://cloud.githubusercontent.com/assets/5695450/18145152/eded761e-6f97-11e6-975a-aa7df298e76b.png)
And here are the ones from example:
![concoct-output_example](https://cloud.githubusercontent.com/assets/5695450/18145161/f75eea7a-6f97-11e6-8c57-8b9849e84d51.png)

Here are the files in my concoct input directory:
![concoct-input_mine](https://cloud.githubusercontent.com/assets/5695450/18145175/0d078a8a-6f98-11e6-9286-460734a61da6.png)
And here are the ones from example:
![concoct-input_example](https://cloud.githubusercontent.com/assets/5695450/18145187/1b618608-6f98-11e6-853a-a91ec6016b43.png)

I found that the file size of my inputs were much larger than the ones in the example. So I went back to prior steps and checked the velvet output file "velvet_71.fa" in the contigs directory.
My contigs directory:
![contigs_mine](https://cloud.githubusercontent.com/assets/5695450/18145253/699f5dcc-6f98-11e6-9025-58d5247362cc.png)
Contigs directory in the example:
![contigs_example](https://cloud.githubusercontent.com/assets/5695450/18145274/7cbbce4a-6f98-11e6-982e-73d5769eead1.png)

It seems like velvet was producing different output (I was using the commands listed in the tutorial) and may be the main reason of leading to 16 clusters... the velvet version that I was using was 1.1.06 but I couldn't figure out the velvet version that CONCOCT 0.4.0 was using since this link isn't working: https://concoct.readthedocs.io/en/README.md#dependencies

Could it be the problem of velvet version or do you have other thoughts? Thanks again for helping!

Best,

Alison

**Comment by alneberg** [comment]
Ok, yes the assembly looks different.

The command you are quoting is actually missing a '*':

cat my/full/path/to/CONCOCT_test_data_0.3.2/reads/Sample_R1.fa > All_R1.fa

should be

cat my/full/path/to/CONCOCT_test_data_0.3.2/reads/Sample*_R1.fa > All_R1.fa

If that's the case for the command you used, it would explain why the result is different. I realize now that the velvet version is not documented, but I believe we used version 1.2.10. However, if it was only small differences in the assembly results I think the version could be an explanation but these differences are so big I think the input data is different.

I would recommend you to rerun the assembly and comparing the new assembly with your previous one, making sure that the files All_R1.fa and All_R2.fa are both around 272M each. If the assembly turns out the same, we have to dig deeper.

Good luck,
Johannes

**Comment by AlisonF** [comment]
Yes I had a typo there, sorry about that. The files All_R1.fa and All_R2.fa are indeed both 272M each:
![all_r1_fa_all_r2_fa](https://cloud.githubusercontent.com/assets/5695450/18178418/3eae0cf8-704c-11e6-8dc7-17f0ad674ffc.png)

I ran the velvet commands again:
velveth velveth_k71 71 -fasta -shortPaired -separate All_R1.fa All_R2.fa
velvetg velveth_k71 -ins_length 400 -exp_cov auto -cov_cutoff auto
and the output (contigs.fa) is **18M** instead of **6.7M** in the example. So I think it's pretty clear that there's something different that velvet is doing...
My contigs.fa under velveth_k71 directory:
![velveth_k71_mine](https://cloud.githubusercontent.com/assets/5695450/18178765/a759c250-704d-11e6-82bd-778e355aa3d4.png)
There is no velveth_k71 directory in the example but velvet output should equal to velvet_71.fa in contigs directory:
![velveth_k71_example](https://cloud.githubusercontent.com/assets/5695450/18178775/b2730372-704d-11e6-8f13-d705f789531a.png)

Here are my standard error and standard output when running velvet:
[velvet_stderr.txt](https://github.com/BinPro/CONCOCT/files/450420/velvet_stderr.txt)
[velvet_stdout.txt](https://github.com/BinPro/CONCOCT/files/450421/velvet_stdout.txt)
Does it look the same to yours? I hope they would make things more clear.

I did another test starting with velvet_71.fa provided in the example and I came up with this plot:
[ClusterPlot_data0.3.2_start_from_velvet_71_fa.pdf](https://github.com/BinPro/CONCOCT/files/450429/ClusterPlot_data0.3.2_start_from_velvet_71_fa.pdf)
Although it still looks a bit different to what the example had, now it has 4 clusters and I guess it's more acceptable.

Please let me know what you think and I highly appreciate your time and help! Thank you.

Best,

Shih-Chen

**Comment by alneberg** [comment]
Hi again @AlisonF,

sorry for not responding in half a year, but I think the clusterplot you achieved in the end is perfectly acceptable don't you?
