### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'no_original_data'

### ISSUE THREAD

**Issue by Skeshani** [BinPro/CONCOCT#164]
Hi,
I'm using CONCOCT for my metagenomic data. I have created successfully the bam files and tables.
my running script is:
/home/sk3389/tools/CONCOCT-master/bin/concoct -c 40 -l 100 --total_percentage_pca 85 --coverage_file ATL_inputtableR.tsv --composition_file /lustre/scratch/sk3389/GroopM/IDBAH_ALT
/contig.fa -b /lustre/scratch/sk3389/CONCOCT/output
However, CONCOCT stopped:
Traceback (most recent call last):
  File "/home/sk3389/tools/CONCOCT-master/bin/concoct", line 77, in <module>
    results = main(args)
  File "/home/sk3389/tools/CONCOCT-master/bin/concoct", line 44, in main
    if not args.no_original_data:
AttributeError: 'Namespace' object has no attribute 'no_original_data
I would apperciate any help.
Thanks,
Saeed

**Comment by alneberg** [comment]
Hi @Skeshani,

sorry for the late reply. I think this problem is due two different versions of concoct being in place. Perhaps you have downloaded the master branch but not reinstalled after updating the repository.  Reinstalling the repo should hopefully fix this issue.
