### ISSUE TITLE
Trouble extracting bins from cluster file with linkage info

### ISSUE THREAD

**Issue by jfrank87** [BinPro/CONCOCT#167]
Dear community,

I am unable to extract bins using a cluster file that includes linkage information. 
Extracting bins without using linkage information works perfectly fine. 
These are the commands I use:

```
# Generate linkage information
bam_to_linkage.py --regionlength 500 --fullsearch --samplenames samples.txt contigs.fa sample1.bam sample2.bam > linkage_concoct.tsv

# Run CONCOCT
concoct --coverage_file cov_concoct.tsv --composition_file contigs.fa -r 250 -b output/

# Incorporate linkage information
ClusterLinkNOverlap.pl --cfile=output/clustering_gt1000.csv --lfile=linkage_concoct.tsv --covfile=cov_concoct.tsv --ofile=output/clustering_gt1000_withLinkage.csv

# Extract bins generated with linkage clustering
extract_fasta_bins.py --output_path bins contigs.fa concoct-output/clustering_gt1000_withLinkage.csv
```

The error message I get is as follows:

```
 Traceback (most recent call last):
   File "extract_fasta_bins.py", line 38, in <module>
       main(args)
         File "extract_fasta_bins.py", line 26, in main
             seqs = [all_seqs[contig_id] for contig_id in contig_ids] 
             KeyError: 1
```

These are the first 5 lines of the cluster file:

```
NODE_18631_length_3186_cov_2.23079,0,1,1
NODE_16895_length_3343_cov_3.08769,0,1,1
NODE_7330_length_5178_cov_16.5029,0,1,1
NODE_7698_length_5038_cov_20.9114,0,1,1
NODE_2209_length_9899_cov_24.4744,0,1,1
```

Did anyone else encounter this problem before? 
Any ideas on how to solve it? Or am I perhaps doing something wrong.. 
All help highly appreciated! Thank you.

Jeroen

Edit: it seems the sourcefourge mailing list is not working (anymore)

**Comment by jfrank87** [comment]
Hi! Unfortunately not. I did not get any support here or through the mailinglist. I also did not try to fix it myself.

**Comment by alneberg** [comment]
Sorry to keep you waiting. The honest answer is that I don't know. The linkage script hasn't been maintained in a few years and we never actually used it since we didn't see an advantage to the clustering results from it compared to just using concoct.

Judging from the Validate.pl script I can decode that the second column contains the cluster id. So you can use this file as a regular clustering file by just disregarding the last two columns.

Cheers,
Johannes
