### ISSUE TITLE
gsl erro

### ISSUE THREAD

**Issue by jianmingli1** [BinPro/CONCOCT#168]
#include "gdal/gdal.h"
#include "gdal/gdal_priv.h"

#include <gsl/gsl_errno.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_min.h>
#include <gsl/gsl_roots.h>
#include <gsl/gsl_spline.h>

#include "src/epr_api.h"

when I compile .cpp file, it shows such error message. 
anybody knows how to solve this?

fatal error: gsl/gsl_errno.h: No such file or directory
compilation terminated.

**Comment by alneberg** [comment]
Seems like the GNU scientific library is not installed or found by the compiler.
