### ISSUE TITLE
Failed to open pca_variances_dimN.csv

### ISSUE THREAD

**Issue by alex-b-chase** [BinPro/CONCOCT#172]
I am running CONCOCT with some assembled metagenomes from soil samples. I used MegaHit for the assembly and everything looked pretty good. Once I tried the binning, however, I get the following error. I still get the expected output file clustering.csv but cannot write the rest?

```
else{
    fprintf(stderr,"Failed to open %s for writing in writeSquareMatrix\n", szFile);
    fflush(stderr);
```
This seems to be an issue once I hit dim122 or greater. I have tried reducing the number of sequences as well and no luck. Any assistance would be greatly appreciated! Thank you!

below is the standard error:

> Up and running. Check concoct-output/log.txt for progress
> 
> Failed to open concoct-output/variances_gt1000_dim123.csv for writing in writeSquareMatrix
> Failed to open concoct-output/pca_variances_gt1000_dim124.csv for writing in writeSquareMatrix
> Failed to open concoct-output/variances_gt1000_dim124.csv for writing in writeSquareMatrix
> Failed to open concoct-output/pca_variances_gt1000_dim125.csv for writing in writeSquareMatrix
> Failed to open concoct-output/variances_gt1000_dim125.csv for writing in writeSquareMatrix
> Failed to open concoct-output/pca_variances_gt1000_dim126.csv for writing in writeSquareMatrix
> Failed to open concoct-output/variances_gt1000_dim126.csv for writing in writeSquareMatrix
> ...
> Failed openining concoct-output/responsibilities.csv in main
> Failed openining concoct-output/vbl.csv in main
>

**Comment by alneberg** [comment]
Hi @alex-b-chase,

this looks strange. I'm suspecting this is due to your file system some how and not a problem within concoct?
