### ISSUE TITLE
How to estimate the "maximum number of clusters" for a soil metagenomics dataset?

### ISSUE THREAD

**Issue by lfaller** [BinPro/CONCOCT#175]
The example you provide mentions to `run concoct with 40 as the maximum number of cluster -c 40, that we guess is appropriate for this data set`.

Soil metagenomics datasets are believed to be very diverse. 

Do you have any advice on estimating maximum cluster numbers?

Thanks!

**Comment by alneberg** [comment]
The default value -c 400 usually works pretty well. The value 40 is used in the tutorial wich is a toy example. The general recommendation is to use approximately 4 times the expected number of genomes present in the input as the value for c. While highly diverse samples increase this value (for the E-coli dataset in the publication we used -c 1000) a lot of the diversity might not be reflected in longer contigs unless it's very deeply sequenced. Hope this helps.

Johannes
