### ISSUE TITLE
CONCOCT v0.4.1 and dnadiff_dist_matrix.py

### ISSUE THREAD

**Issue by bioinfo17** [BinPro/CONCOCT#176]
Hi,

Where could I download v0.4.1? Also dnadiff_dist_matrix.py is not found under /scripts in the older versions/releases of CONCOCT? Is it OK to download the dnadiff_dist_matrix.py script and work with older releases?

Thanks

**Comment by alneberg** [comment]
Version 0.4.1 is what's availble if you clone the repository and using the master branch. The script dnadiff script was added in version 0.4.1 and is therefore not available in the previous versions. I think it's fine to use the script with older versions yes.
