### ISSUE TITLE
Add option for # of threads

### ISSUE THREAD

**Issue by snayfach** [BinPro/CONCOCT#177]
Maybe I missed it, but it would be useful to be able to specify the # of threads the program uses. It looks like it uses 10 by default.

Thanks,
Stephen

**Comment by alneberg** [comment]
Hi Stephen,

sorry to keep you waiting. We're working on a new truly parallel version of Concoct available in the branch SpeedUpMp where you can adjust the number of threads.

Previously, the ten threads of concoct all perform one run of the clustering, all initialised randomly, the clustering output is chosen as the best of these ten runs. Therefor adjusting the number of threads in the current version would affect the performance as well.

Cheers,
Johannes
