### ISSUE TITLE
Mailing list located at: concoct-support@lists.sourcefourge.net does not work

### ISSUE THREAD

**Issue by aimirza** [BinPro/CONCOCT#183]
I tried sending a message to concoct-support@lists.sourcefourge.net but the message is not delivering. Who can we email to address our problems using CONCOCT?

**Comment by alneberg** [comment]
Yes, this is now replaced by the gitter channel: https://gitter.im/BinPro/CONCOCT. Otherwise posting a question here as an issue is also an alternative.
