### ISSUE TITLE
Issue with "concoct --coverage_file"

### ISSUE THREAD

**Issue by aimirza** [BinPro/CONCOCT#184]
Dear CONCOCT crew,

concoct --coverage_file has been running for weeks and the file clustering_gt1000.csv was never created. Only the following files were created: original_data_gt1000.csv,  PCA_components_data_gt1000.csv, PCA_transformed_data_gt1000.csv, log.txt, and args.txt. I have 22 seawater metagenomic samples. I have been following the Supplementary materials from Quince et al. Metagenome analysis Review: https://github.com/chrisquince/metag-rev-sup . I have included the files for the code (Coverage.tsv and all_contigs_c10K.fa)

[all_contigs_c10K.fa](https://drive.google.com/file/d/1a_bC-oKSfrPosJ_TZKSxqusToBREw0bY/view)
[Coverage.tsv](https://drive.google.com/file/d/15cxQideajSHzbuK_yXw8vdzPdogDAJxS/view)
 
Code:
python ~/CONCOCT/bin/concoct --coverage_file Coverage.tsv --composition_file ../3.Red_Sea_Shotgun_Assembly/contigs/all_contigs_c10K.fa

log.txt:
2017-12-08 10:54:53,077:INFO:root:Results created at /home/amirza/Red_sea/concoct
2017-12-08 11:40:37,441:INFO:root:Successfully loaded composition data.
2017-12-08 11:43:06,722:INFO:root:Successfully loaded coverage data.
2017-12-08 11:46:00,202:INFO:root:Performed PCA, resulted in 66 dimensions
2017-12-08 12:03:06,187:INFO:root:Wrote original filtered data file.
2017-12-08 12:09:57,018:INFO:root:Wrote PCA transformed file.
2017-12-08 12:09:57,032:INFO:root:Wrote PCA components file.
2017-12-08 12:09:57,032:INFO:root:PCA transformed data.
2017-12-08 12:09:57,033:INFO:root:Will call vbgmm with parameters: ./, 400, 1000

My cluster error output says:
Up and running. Check /home/amirza/Red_sea/concoct/log.txt for progress
/home/amirza/.conda/envs/concoct_env/lib/python2.7/site-packages/Bio/Seq.py:341:
 BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) in
stead of my_seq.tostring().
  BiopythonDeprecationWarning)

Your help will be much appreciated!

**Comment by SamLambrechtsUGent** [comment]
Dear aimirza,

Were you able to fix this? I have the same error output.

Best,

Sam

**Comment by alneberg** [comment]
Hello @SamLambrechtsUGent, this should be much faster with the new version of concoct (v1.0.0). For how long have your run been up?

**Comment by SamLambrechtsUGent** [comment]
Hello Johannes, thank you for your comment. In the meantime concoct finished successfully. It was the first time I tried concoct, and I was alarmed by the BiopythonDeprecationWarning, thinking that concoct had stopped working and I had to fix my biopython. But this was not the case apparently, concoct was running fine
