### ISSUE TITLE
clustering_gt1000.csv contigs suffixed with .0, .1, ...

### ISSUE THREAD

**Issue by kengcher** [BinPro/CONCOCT#185]
I assembled the contigs using megahit and then binned them using concoct, however i see that there are entries in the clustering_gt1000.csv that correspond to the actual_contig_name k141_4933 suffixed with .0, .1, .2? What do they mean as there are no contigs with those suffixes in the contigs file.

k141_4933.0 | 4
k141_4933.1 | 4
k141_4933.2 | 14

Thank you.

**Comment by alneberg** [comment]
These suffices are added by the `cut_up_fasta.py` script and correspond to the different parts of the original contigs. The clustering of the original contigs can be retrieved using the `merge_cutup_clustering.py` script.
