### ISSUE TITLE
issues about concoct

### ISSUE THREAD

**Issue by Shirley-Q** [BinPro/CONCOCT#186]
I do this command：concoct -c 40 --coverage_file concoct-input/concoct_inputtableR.tsv --composition_file contigs/velvet_71_c10K.fa -b concoct-output/
Then I have something error：
![screenshot from 2018-03-16 19_28_08](https://user-images.githubusercontent.com/30583482/37519198-305e4fc0-2953-11e8-9b1b-8596117d63fa.png)
And I can not deal with it,I need you  help,thanks!

**Comment by alneberg** [comment]
Hi @qiaoxuejiao,

most likely, something is wrong with your coverage file. Check that it looks correct and ensure that it has tab separated columns. If you find no error, I will have to look into this error more closely, preferably using input files where you can replicate the problem.

Best Wishes,
Johannes

**Comment by qiaoxuejiao** [comment]
Hi @alneberg,
I can not find error, Could you help me look into this error more closely, thanks!


[sample1_L1_concoct_inputtableR.pdf](https://github.com/BinPro/CONCOCT/files/1821159/sample1_L1_concoct_inputtableR.pdf)

Best wishes,
Xuejiao

**Comment by alneberg** [comment]
Woah! A thousand pages pdf! I think the problem could be that the contig ids are digits only. We've had this issue before, could you try adding for example "contig_" before all contig ids.

Hope this will work.
Johannes

**Comment by qiaoxuejiao** [comment]
I adding for example "contig_" before all contig ids following your instructions, but I have same error.
now I do whole process, and I have another error. I need your help.
![error](https://user-images.githubusercontent.com/30583482/37637650-d5e4f190-2c43-11e8-95ff-31ac9cd4f836.png)

**Comment by qiaoxuejiao** [comment]
Hi,
I want to know where are bins.
This is my content of concoct-output file:
![error](https://user-images.githubusercontent.com/30583482/37712659-7e5c353e-2d4f-11e8-9ae9-b21a59fcd712.png)
Thanks very much!

**Comment by alneberg** [comment]
Hi again @qiaoxuejiao,

the ClusterPlot.R issue is a know issue which is fixed in the latest online version of the script:
https://github.com/BinPro/CONCOCT/blob/master/scripts/ClusterPlot.R

Your clustering results are available in the clustering_gt1000.csv file.

In order to get the clusters in fasta format you can use the script:

https://github.com/BinPro/CONCOCT/blob/master/scripts/extract_fasta_bins.py

But if you used the cut_up_fasta.py script you probably want to merge the clustering first, you can do that using:
https://github.com/EnvGen/toolbox/blob/master/scripts/concoct/merge_cutup_clustering.py

Best Wishes,
Johannes

**Comment by qiaoxuejiao** [comment]
Hi,
When I python merge_cutup_clustering.py, it have something wrong.
Are there something wrong about my usage?
![screenshot from 2018-03-23 12_56_28](https://user-images.githubusercontent.com/30583482/37812464-21c0cc3e-2e9b-11e8-95f0-8a4fe19f6fe4.png)
Thank you very much！

**Comment by alneberg** [comment]
Yes you should run that script on the clustering file and not the original fasta file.

Johannes

**Comment by qiaoxuejiao** [comment]
Hi @alneberg,
I want to determine the most suitable number of genomes. What should I do?

**Comment by alneberg** [comment]
In most cases you're fine running with the default parameter '-c 400'. If you have both highly diverse samples AND very deeply sequenced samples, you could increase this number.
