### ISSUE TITLE
Concoct run doesn't end?

### ISSUE THREAD

**Issue by rotoscan** [BinPro/CONCOCT#187]
Hello,

I've been using CONCOCT for a while now and I have encountered some problem dealing with some data. The last step (~/CONCOCT-0.4.0/bin/concoct -c <i1>  --coverage_file  <i2> --composition_file <i3> -b <i4> -o # such that, from i1 to i4, are the inputs for the command).

I have tried to run CONCOCT a few times and it simply runs many days. I realized I wasn't giving any input on the -c parameter, such that number of clusters was set to default (400). Does this affect the calculation time? How can  I determine the best -c input for my data?

Thank you very much for the attention!
Rodolfo Toscan

**Comment by alneberg** [comment]
Hello @msbufz,

yes I'm afraid long run times for concoct version 0.4.0 is expected if you have a reasonably large input data set. If you have access to a large number of cpu:s on your computer/server I would recommend you to try to install the version available in the SpeedUp_Mp branch. It is not an official version yet and lack in documentation, but it has been tested and the results are comparable to the original version.

I believe a recommendation given in the original paper is to use approximately four times as many initial clusters as you would expect to get as resulting clusters. Although, I would say the default "-c 400" works for most cases.

Best Wishes,
Johannes

**Comment by aimirza** [comment]
I have the same problem except that my job runs for weeks. I posted a similar issue about a month ago, still waiting for the response: https://github.com/BinPro/CONCOCT/issues/184

**Comment by alneberg** [comment]
Hi @aimirza, sorry for not replying to your issue sooner. The same answer goes for you as above. The old version of concoct starts off running with 10 threads and each thread terminates when the clustering is finished. Can you check how many threads you still have running with for example 'htop'?

Johannes
