### ISSUE TITLE
cut_up_fasta.py error

### ISSUE THREAD

**Issue by nafeesatk** [BinPro/CONCOCT#188]
When trying to use the cut_up_fasta.py script with my data or the example data (using the same parameters outlined in the example), it results in the same error:

  File "/home/nk/Applications/CONCOCT-0.4.0/scripts/cut_up_fasta.py", line 14
    print ">%s.%i\n%s" % (record.id, i, split_seq)
                     ^
SyntaxError: invalid syntax

The new file generated as a result is blank. How should I fix this? Is there something wrong in the way that I am using the script?

Thank you!

**Comment by alneberg** [comment]
Hello @nafeesatk,

this looks like a python 3 vs python 2 problem. From the error message I'm assuming you're using python version 3.x, could you try running the script with python version 2?

Best wishes,
Johannes
