### ISSUE TITLE
Questions about Validate.pl output and Cluster plot

### ISSUE THREAD

**Issue by franciscozorrilla** [BinPro/CONCOCT#193]
When I run the Validate.pl as shown in the readthedocs example, I obtain the following output:

N        M        TL                  S     K     Rec.              Prec.              NMI               Rand               AdjRand
683     11      9.1490e+04    1     5     0.707116     1.000000        0.000000        0.585789        0.000000

Instead of the expected:

N       M        TL                   S   K   Rec.            Prec.           NMI            Rand          AdjRand
684    684     6.8023e+06    5   4   0.897224    0.999604    0.841911    0.911563    0.823200

Most notably, the NMI and AdjRand indexes I obtained are 0. But also the number of clusters with labels M is significantly lower in my results. What could be the reason behind these discrepancies? Some incorrect usage of CONCOCT perhaps? 

My cluster plot also looks different than the one shown in the example. Most notably, I seem to have an extra species cluster present:

[ClusterPlot.pdf](https://github.com/BinPro/CONCOCT/files/2093609/ClusterPlot.pdf)

What could be the reason behind this extra species cluster?

I am running the exact commands from the complete example V0.4 and using the provided dataset.

**Comment by alneberg** [comment]
Hi @franciscozorrilla,

just to be clear, the clustering run you are trying to calculate the stats for is the same data as in the tutorial, am I right?

According to the stats you only have 11 contigs with a species label and only 1 unique such species label. It could be an error due to file parsing for example.

Can you please double check the command for running Validate.pl? 

Regarding the clusterplot, I think it looks ok, the clustering is indeed different, but you can see the extra cluster also in the Validate.pl results (K=5). I think this definitely lies within the margins of randomness within concoct, especially when taking into account that the versions of scipy and such dependencies might be very different.

Please come back with more information regarding the Validate.pl run, which I indeed think looks strange.

**Comment by franciscozorrilla** [comment]
Hey @alneberg, thanks for responding!

Yes, I am following the tutorial and using the data in the folder CONCOCT-test-data-0.3.2/reads

The following is my command for running Validate.pl:

{config[paths][CONCOCT]}/scripts/Validate.pl --cfile=concoct-output/clustering_gt1000.csv --sfile=evaluation-output/clustering_gt1000_s.csv --ofile=evaluation-output/clustering_gt1000_conf.csv --ffile=contigs/velvet_71_c10K.fa

I have been looking through my pipeline to try and pinpoint where my results start to differ significantly from what is shown in the tutorial example, and it looks like the concoct_inputtable.tsv I obtain is different from what i see in CONCOCT-complete-example. My guess is that the differences are due to MarkDuplicates or bowtie maybe?

Please let me know if you would like any additional information.

**Comment by alneberg** [comment]
Hi @franciscozorrilla,

did you rerun the assembly as well? In that case, the file evaluation-output/clustering_gt1000_s.csv might not have the same contig labels as yours and thereby causing the problems with Validate.pl

Yes it is very likely that versions of bowtie and markduplicates are not identical and thus the results might differ. As confusing this might be, I don't think it is a problem for your data as the clustering looks reasonably good, I think everything seems to work ok.

You should also remember that these final steps basically only applies to the test dataset. For a real dataset you will be much better of using CheckM or Anvi'o to validate your clusters after running a binning software. Calculating statistics based on taxonomic labels rarely work on real data as the taxonomic labelling is usually not that accurate.

Cheers,
Johannes

**Comment by franciscozorrilla** [comment]
Hi @alneberg, sorry for the late response!

I did in fact run the assembly myself, thank you for the explanation.
Also thank you for the suggestions, I will check out those tools!

Kind regards,
Francisco
