### ISSUE TITLE
Example of concoct workflow

### ISSUE THREAD

**Issue by johanneswerner** [BinPro/CONCOCT#194]
I was following the [workflow](https://concoct.readthedocs.io/en/latest/complete_example.html#map-the-reads-onto-the-contigs) to run concoct on one of my samples but I faced problems when mapping the reads back to the contigs, more precisely here: 

I installed concoct and picard via conda. 

```
export MRKDUP=/home/username/src/picard-tools-1.77/MarkDuplicates.jar
for f in $CONCOCT_TEST/reads/*_R1.fa; do
    mkdir -p map/$(basename $f);
    cd map/$(basename $f);
    bash $CONCOCT/scripts/map-bowtie2-markduplicates.sh -ct 1 -p '-f' $f $(echo $f | sed s/R1/R2/) pair $CONCOCT_EXAMPLE/contigs/velvet_71_c10K.fa asm bowtie2;
    cd ../..;
done
```
Picard is now available in version 2.18.7 and has no script MarkDuplicates.jar anymore. 

Can you help me out here? Or is there another possibility to create the coverage and the linkage table and run concoct?

Thank you for your help. If you require any additional information, please ask.

**Comment by johanneswerner** [comment]
Just saw, that this is a duplicate of this [comment](https://github.com/BinPro/CONCOCT/issues/180#issuecomment-380745917) in issue #180.

**Comment by alneberg** [comment]
The coverage table can now be created from a set of bam files and no specific script for mapping is longer recommended.
