### ISSUE TITLE
CONCOCT bins are not complete and contaminated

### ISSUE THREAD

**Issue by zahidrehman** [BinPro/CONCOCT#195]
Dear Alneberg, I have only two samples (biofilm) and using anvio metagenomic workflow for analyses. In the end, I got some 28 bins but only one bin(bin_5) has completion of 93.5%. Rest of all the bins have completion less than 10%, even though they are bigger in size (5Mbp)( e.g Bin_1, Bin_2). Do you think small sample number is causing an issue with binning?  I have attached a screenshot of anvio interactive.
Best Regards
Zahid

<img width="1420" alt="screen shot 2018-07-30 at 4 53 32 pm" src="https://user-images.githubusercontent.com/41961425/43466112-7dbc187e-94e7-11e8-82f0-5c72576caa89.png">

**Comment by alneberg** [comment]
Dear Zahid,

yes I think two samples are usually too few to get a good binning performance with concoct. If you know any similar datasets I would try to include those for quantification. 

Another possibility is that there are eukaryotic or viral bins, which would not be detected as complete or contaminated by the regular prokaryotic single copy gene sets.

Good luck!
