### ISSUE TITLE
Extracting bins returns an error (KeyError)

### ISSUE THREAD

**Issue by gelomerase** [BinPro/CONCOCT#204]
Hi,

I've been trying to extract binned contigs using the `extract_fasta_bins.py` script but I get the following error:
```
Traceback (most recent call last):
  File "extract_fasta_bins.py", line 38, in <module>
    main(args)
  File "extract_fasta_bins.py", line 26, in main
    seqs = [all_seqs[contig_id] for contig_id in contig_ids]
  File "extract_fasta_bins.py", line 26, in <listcomp>
    seqs = [all_seqs[contig_id] for contig_id in contig_ids]
KeyError: 'k127_129658'
```

For reference, my clustering file is formatted as:
```
k127_299010,109
k127_299011,148
k127_16216,75
k127_246325,129
k127_455900,49
```

I have no idea what I'm doing wrong so any help would be appreciated.

**Comment by alneberg** [comment]
Hello!

From a quick glance, it seems the contig 'k127_129658' can't be located within your fasta file. Is it the same you used as input to concoct? For further debugging, could you post your exact command for the script?

**Comment by jiangshf5** [comment]
I have encountered the same problem. Have you solved it ?
