### ISSUE TITLE
Question about parameter used in complete example

### ISSUE THREAD

**Issue by franciscozorrilla** [BinPro/CONCOCT#205]
Im not sure if this is the best place to leave this question, but here it goes.

On the readthedocs complete example page you guys use a hash length of 71 when running the velveth step.
I was wondering how you decided to use this value? and if you would recommend to tweak it based on different data sets being examined?

Thanks,
Francisco

**Comment by alneberg** [comment]
Hi @franciscozorrilla,

this specific question is probably only suitable to @inodb. But I guess it's just to allow slightly longer kmers than the standard velvet.

However, we do not recommend using velvet in a real setting. We recommend using [megahit](https://github.com/voutcn/megahit) which is a much more modern metagenomics assembler. Sorry for not keeping the tutorial up to date.

**Comment by franciscozorrilla** [comment]
Hey @alneberg @inodb 

Thanks for your response! Yes my PI actually suggested the same thing a while ago but I must have forgotten to implement the change in my pipeline. Cheers!
