### ISSUE TITLE
Problem with installation by conda

### ISSUE THREAD

**Issue by bioinformatist** [BinPro/CONCOCT#227]
Dear, I've noticed that the software came to v1.0.0, and it supports python 3.X now. So I just tried `conda install concoct` and everything looked well durining installation. However, when I tried command `concoct`, it throwed an error:

```pre
Traceback (most recent call last):
  File "/share/home/lzhiwei/.conda/envs/ysun-env/bin/concoct", line 6, in <module>
    import vbgmm
ImportError: /share/home/lzhiwei/.conda/envs/ysun-env/lib/python3.6/site-packages/vbgmm.cpython-36m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule
```

It seems like a problem caused by library vbgmm. I try install it by `pip` or `conda`, but both of them say no proper version here. The python version is v3.6.7 in the virtual env. Can you help me?

**Comment by alneberg** [comment]
Yes, unfortunately the conda package is still not ready to be merged, you can keep track of the progress here:
https://github.com/bioconda/bioconda-recipes/pull/12600

At least to begin with, macosx will not be supported, so if you are running a mac, you might need to do a specific install still. Please let me know if you need further assistance with that.

**Comment by bioinformatist** [comment]
Wow, what a quick reply! I'm using x86-64 Linux on HPC (you know, I'm not the one so conda makes things easier), and I'll keep concern with this recipe. Once it finished I would like try again with 3.x python and give you a response. Thanks for attention for this problem~

**Comment by bioinformatist** [comment]
Ahhhhh, thank you!
The software by `conda install` with Linux and py3 works well now.
And it seems samtools is already satisfied up to now~
Concoct is one of best binning softwares 😆

**Comment by alneberg** [comment]
Very pleased to hear! Just remember to set the `-t` flag to get the proper performance.

**Comment by ReneKat** [comment]
Hi @alneberg:
I'm over here now. :) 
I have the latest versions of concoct and samtools installed and am getting the same error above:
# packages in environment at /Users/Owl/miniconda3/envs/concoct_env:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
biopython                 1.74             py36h0b31af3_0    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py36_0    conda-forge
cffi                      1.13.2           py36h33e799b_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
concoct                   0.4.1            py36hd1ccf6d_0    bioconda
cryptography              2.8              py36hafa8578_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
cython                    0.29.14          py36h4a8c4bd_0    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
gsl                       2.2.1                h002c638_3  
htslib                    1.9                  h3a161e8_7    bioconda
idna                      2.8                   py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.0                     py_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                h89e68fa_1    conda-forge
libdeflate                1.0                  h1de35cc_1    bioconda
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1                         1    bioconda
libgfortran               3.0.1                         0    conda-forge
liblapack                 3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                hdc02c5d_2  
libssh2                   1.8.2                hcdc9a53_2    conda-forge
llvm-openmp               9.0.0                h40edb58_0    conda-forge
markupsafe                1.1.1            py36h0b31af3_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
nose                      1.3.7                 py36_1003    conda-forge
numpy                     1.17.3           py36hde6bac1_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py36h4f17bb1_0    conda-forge
pip                       19.3.1                   py36_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.7             h4285619_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
samtools                  1.9                 h8aa4d43_12    bioconda
scikit-learn              0.21.3           py36hd4ffd6c_0    conda-forge
scipy                     1.3.1            py36hab3da7d_2    conda-forge
setuptools                41.6.0                   py36_1    conda-forge
six                       1.13.0                   py36_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    2.2.1                      py_0    conda-forge
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge

`concoct --composition_file cSMMC_contigs_10K.fa --coverage_file cSMMC_coverage_table.tsv -b concoct_output/`

Traceback (most recent call last):
  File "/Users/Owl/miniconda3/envs/concoct_env/bin/concoct", line 6, in <module>
    import vbgmm
ImportError: dlopen(/Users/Owl/miniconda3/envs/concoct_env/lib/python3.6/site-packages/vbgmm.cpython-36m-darwin.so, 2): Symbol not found: _Py_InitModule
  Referenced from: /Users/Owl/miniconda3/envs/concoct_env/lib/python3.6/site-packages/vbgmm.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/Owl/miniconda3/envs/concoct_env/lib/python3.6/site-packages/vbgmm.cpython-36m-darwin.so

**Comment by alneberg** [comment]
Hi @ReneKat,

I can see in your list of packages that you're using concoct 0.4.1. Can you consider to upgrade to the latest version instead?

Thank you,
Johannes

**Comment by ReneKat** [comment]
Hello Johannes (@alneberg),
I can see from the change log that you're on version 1.1.0! So, yes my version is quite behind. However, when I run
` conda update concoct`
I get:
# All requested packages already installed.

When I run:
`concoct -v`
I get the above error again. 

I have only ever installed packages using conda. I'm running MacOS 10.14.6.

**Comment by alneberg** [comment]
There are some issues with the concoct conda build recipe where it is quite specific with some dependencies. I think the easiest way is to make completely new environment. Just follow the installations instructions again: https://concoct.readthedocs.io/en/latest/installation.html

It should be fairly quick. If you have something else in your current environment you can always switch between the two different environments (as long as you give them different names).

**Comment by mant-ux** [comment]
@bioinformatist Hello！I  have the same problem as you after install it by Bioconda.
<img width="587" alt="image" src="https://user-images.githubusercontent.com/82646017/118609717-98958500-b7ed-11eb-942c-282facc90404.png">
I have follow our author run **conda install concoct samtools** ,But it still reported an error. How did you run it successfully? Can you give me some help? I'm confused with **vbgmm**, Thank you very much.
