### ISSUE TITLE
Arguments not longer used

### ISSUE THREAD

**Issue by alneberg** [BinPro/CONCOCT#239]
The number of iterations given by the user is ignored. So is epsilon. These parameters are rather complex and it might not be necessary to give users access to them. But the current way to handle it is faulty nevertheless.

**Comment by chrisquince** [comment]
Well this is an easy thing to change as it is all in the python wrapper, let me look at it...

**Comment by alneberg** [comment]
The max iterations parameter is now working again thanks to c21349bdbe68139e82fa81dc7e14e5e8679a72a3. The epsilon parameter is still not useable, but we might as well remove that as an option, I haven't come across any time where this parameter should be adjusted.
