### ISSUE TITLE
KeyError when using fasta_to_features.py

### ISSUE THREAD

**Issue by Ash1One** [BinPro/CONCOCT#249]
Hello, 
error returned when I try to generate composition table 
```
Traceback (most recent call last):
  File "/home/biosoft/CONCOCT/scripts/fasta_to_features.py", line 56, in <module>
    generate_features_from_fasta(fasta_file,nr_datapoints,kmer_len,outfile)
  File "/home/biosoft/CONCOCT/scripts/fasta_to_features.py", line 40, in generate_features_from_fasta
    contigs[i,kmer_dict["".join(kmer_tuple)]] += 1
KeyError: 'AAGR'
```
should I replace the letters other than ATCG in my co-assembly file ?
Thanks!

**Comment by alneberg** [comment]
Hello @Ash1One, yes concoct can only use the standard kmers currently, so replacing the non-ATCG characters is needed. Are some assembly programs actually giving out such contig sequences?

**Comment by Ash1One** [comment]
Hi @alneberg ,actually the contig sequences is `goldStandAssemly.fasta` from CAMI. 
Thank you for your answer.😀
