### ISSUE TITLE
Using CONCOCT to determine coverage of specific predicted ORFs in multiple samples

### ISSUE THREAD

**Issue by slvrshot** [BinPro/CONCOCT#270]
I ran across this software when I was researching the `map-bowtie2-markduplicates.sh` tool described in https://buildmedia.readthedocs.org/media/pdf/metagenomics-workshop/2014-5/metagenomics-workshop.pdf file. I have some nucleotide sequences of predicted ORFs from prodigal and would like to determine the read coverage for these genes for each one of my samples (total of 28, divided into 4 groups). I have mapped my reads to the ORFs using bowtie2 and produced multiple sam files for each sample. Ultimately, I'd like to merge these datasets an create an ORF coverage matrix. Would CONCOCT be the right tool for this?

**Comment by alneberg** [comment]
Hi @slvrshot, there are many ways of accomplishing this. CONCOCT is not designed for this task specifically and I will have to refer you on to any these biostars questions:
https://www.biostars.org/p/5165/
https://www.biostars.org/p/201722/

I hope you find what you're looking for there.
