### ISSUE TITLE
concoct on long reads and hybrid assemblies 

### ISSUE THREAD

**Issue by MChiaraC** [BinPro/CONCOCT#279]
Hi, is there any chance concoct can work with assembly and coverage info coming from long reads only? Or short paired reads are the only ones working for this algorithm? 
In this second case should I bin hybrid assemblies using only short reads or is there still somehow a probability of bias?

Thanks!

**Comment by alneberg** [comment]
Hi @MChiaraC,

I think the coverage is the important thing here, if you have deep seequencing of long reads, it *should* work in theory (untested). But I guess the normal case is that you have quite low coverage from only long reads.

A hybrid assembly where the short reads are used for coverage estimation should work fine and sounds like a great idea if you have access to that kind of data. There's always probability of bias, don't dare to speculate in that...
