### ISSUE TITLE
vbgmm import error

### ISSUE THREAD

**Issue by gwendolin** [BinPro/CONCOCT#294]
Hi,

I saw a couple similar issues to this one on the forum, but I haven't been able to fix it myself. I am getting this error when trying to run concoct -h:

(concoct_env) science@SC-Bioinformatics:~$ concoct -h
Traceback (most recent call last):
  File "/home/science/miniconda3/envs/concoct_env/bin/concoct", line 6, in <module>
    import vbgmm
ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory

I downloaded the latest version of concoct with conda as described in the installation docs. My operating system is Linux Mint v20 (Ulyana)
And this is what I get with conda list:

(concoct_env) science@SC-Bioinformatics:~$ conda list
 # packages in environment at /home/science/miniconda3/envs/concoct_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
biopython                 1.78             py38h1e0a361_1    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h924ce5b_2    conda-forge
concoct                   1.1.0            py38h7be5676_2    bioconda
cython                    0.29.21          py38h348cfbe_1    conda-forge
gsl                       2.6                  hf94e986_0    conda-forge
htslib                    1.11                 hd3b49d5_0    bioconda
joblib                    0.17.0                     py_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           2_h86c2bf4_netlib    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
liblapack                 3.9.0           2_h86c2bf4_netlib    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
ncurses                   6.2                  he1b5a44_2    conda-forge
nose                      1.3.7                   py_1006    conda-forge
numpy                     1.19.2           py38hf89b668_1    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    1.1.4            py38h0ef3d22_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
samtools                  1.11                 h6270b1f_0    bioconda
scikit-learn              0.23.2           py38h5d63f67_2    conda-forge
scipy                     1.5.3            py38hb2138dd_0    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
`
Any help would be greatly appreciated!
Tagging my colleague for reference: @DavidGeeraerts

**Comment by DavidGeeraerts** [comment]
(Cc @gwendolin )

Is it odd that the `libmkl_rt.so` is pointing to a file path that doesn't exist?
[`"filepath": "/home/ogrisel/miniconda3/envs/tmp/lib/libmkl_rt.so"`]

Seems like this might be the issue?

![image](https://user-images.githubusercontent.com/5765941/98135754-0f33ec00-1e75-11eb-87cd-23d5e461481b.png)

This might explain why `concoct --help` doesn't even work?

![image](https://user-images.githubusercontent.com/5765941/98136312-a7ca6c00-1e75-11eb-95b0-d246e44a25de.png)

**Comment by cwood15** [comment]
Hello,

I seem to be having the same issue. When I try to run concoct I get the error:
Traceback (most recent call last):
File "/home/cwood15/anaconda3/envs/concoct_env/bin/concoct", line 6, in
import vbgmm
ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory

My input was: concoct --composition_file contigs_10K.fasta --coverage_file coverage_table.tsv -b concoct_output

I installed concoct using the recommended bioconda installation on https://concoct.readthedocs.io/en/latest/installation.html

Here is my conda environment

packages in environment at /home/cwood15/anaconda3/envs/concoct_env:
Name Version Build Channel
_libgcc_mutex 0.1 main
biopython 1.78 py38h1e0a361_1 conda-forge
blas 1.0 mkl
bzip2 1.0.8 h516909a_3 conda-forge
c-ares 1.11.0 h470a237_1 bioconda
ca-certificates 2020.6.20 hecda079_0 conda-forge
certifi 2020.6.20 py38h924ce5b_2 conda-forge
concoct 1.1.0 py38h7be5676_2 bioconda
cython 0.29.21 py38h348cfbe_1 conda-forge
gsl 2.6 hf94e986_0 conda-forge
htslib 1.11 hd3b49d5_0 bioconda
joblib 0.17.0 py_0 conda-forge
krb5 1.17.1 hfafb76e_3 conda-forge
ld_impl_linux-64 2.33.1 h53a641e_7
libblas 3.9.0 1_h6e990d7_netlib conda-forge
libcblas 3.9.0 2_h6e990d7_netlib conda-forge
libcurl 7.71.1 hcdd3856_8 conda-forge
libdeflate 1.6 h516909a_0 conda-forge
libedit 3.1.20191231 h14c3975_1
libev 4.33 h516909a_1 conda-forge
libffi 3.3 he6710b0_2
libgcc-ng 9.1.0 hdf63c60_0
libgfortran-ng 7.5.0 hae1eefd_17 conda-forge
libgfortran4 7.5.0 hae1eefd_17 conda-forge
liblapack 3.9.0 2_h6e990d7_netlib conda-forge
libnghttp2 1.41.0 hab1572f_1 conda-forge
libssh2 1.9.0 hab1572f_5 conda-forge
libstdcxx-ng 9.1.0 hdf63c60_0
llvm-openmp 8.0.1 hc9558a2_0 conda-forge
ncurses 6.2 he6710b0_1
nose 1.3.7 py_1006 conda-forge
numpy 1.19.4 py38hf0fd68c_0 conda-forge
openmp 8.0.1 0 conda-forge
openssl 1.1.1h h516909a_0 conda-forge
pandas 1.1.4 py38h0ef3d22_0 conda-forge
pip 20.2.4 py_0 conda-forge
python 3.8.5 h7579374_1
python-dateutil 2.8.1 py_0 conda-forge
python_abi 3.8 1_cp38 conda-forge
pytz 2020.4 pyhd8ed1ab_0 conda-forge
readline 8.0 h7b6447c_0
samtools 1.11 h6270b1f_0 bioconda
scikit-learn 0.23.2 py38h5d63f67_2 conda-forge
scipy 1.5.3 py38h828c644_0 conda-forge
setuptools 49.6.0 py38h924ce5b_2 conda-forge
six 1.15.0 pyh9f0ad1d_0 conda-forge
sqlite 3.33.0 h62c20be_0
threadpoolctl 2.1.0 pyh5ca1d4c_0 conda-forge
tk 8.6.10 hbc83047_0
tzdata 2020d h14c3975_0
wheel 0.35.1 py_0
xz 5.2.5 h7b6447c_0
zlib 1.2.11 h7b6447c_3

Any help would be greatly appreciated! Thank you!

Claudia

**Comment by DavidGeeraerts** [comment]
@alneberg @binnisb @inodb
Are you still maintaining this project?

**Comment by alneberg** [comment]
@DavidGeeraerts, I'm listening at least. 

I am not able to help out much at this point. I believe this is related to the bioconda recipe: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/concoct  which has been acting up several times over the years. I would be happy to merge in any fix if someone is able to find out what's going wrong.

**Comment by gwendolin** [comment]
Solved this issue by navigating to the bin and installing the mkl library:
`/home/science/miniconda3/envs/concoct_env/bin
pip install mkl`

Then everything works!

**Comment by mant-ux** [comment]
@gwendolin Hello！I have the same problem as you after install it by Bioconda.
image
I have follow you /home/science/miniconda3/envs/concoct_env/bin pip install mkl and run conda install concoct samtools ,But it still reported an error. How did you run it successfully? Can you give me some help? I'm confused with vbgmm, Thank you very much.

**Comment by gwendolin** [comment]
@mant-ux you will need to install the mkl library in the bin inside your conda environment. Your filepath won’t be the exact same as mine.
